kind: pipeline
name: lfs

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
  
  
steps:
  - name: init
    commands:
      - chmod -R +x /drone/src/
      - /drone/src/version-check.sh
      - /drone/src/install_requirements.sh
