kind: pipeline
name: lfs

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
  
  
steps:
  - name: build
    image: ubuntu:latest	
    commands:
      - cd /drone/src/
      - export SRC=/drone/src
      - bash entry_point.sh
